#include "App.h"

#include <iostream>

int main()
{
    App app;

    try
    {
        app.run();
    }
    catch(const std::exception& e)
    {
        std::cerr << e.what() << '\n';
    }
    catch(...)
    {
        std::cerr << "Unknown error occurred!" << '\n';
    }

    return 0;
}